### ISSUE TITLE
Login UI

### ISSUE THREAD

**Issue by alejandrojsuazohvd** [MoneyWise2020/MoneyWise2020#2]
As a moneywise user, I want different users so that my finances can be kept separate.

Additional Details:
Note: this is NOT making data secure, it's just on the UI side. There should be no work on the API side for this story.

For UI side, best to follow this: https://auth0.com/blog/complete-guide-to-react-user-authentication/#Calling-an-API (early commits had this working - I have a copy, this isn't too tricky to work out)

- [x] Should get token. API requests should supply token.
- [x] userid should be provided. This will be replaced later.
- [x] Login and logout buttons at the top right.
- [x] If no one is logged in, the user should not be able to see the content of the plan page.
- [x] If you are not logged in and click on the plan page, you should be prompted to login

Acceptance Criteria:
- Demo: UI with login capabilities.
- Performance: login should be smooth to a reasonable user
- Security: n/a
- Testing: manually tested

**Comment by alejandrojsuazohvd** [comment]
- User login screen (James says: Auth0, have this)
- API Authentication (James says: Auth0, have this)
- Database design for user information
- Schema modeling
        -- “Users”: (might be mostly handled by Auth0)
        -- “Rules”: configured by user, recurring
        -- “Instances”: results derived from rules

**Comment by jamesfulford** [comment]
5 pts
Login: As a moneywise user, I want a landing page for my login to enter my credentials.
Additional details
User login screen (James says: Auth0, have this)
Acceptance Criteria
Demo: UI with login form.
______________________________________________________
8 pts
Authentication: As a moneywise user, I want user authentication so that my finances can be kept private.
Additional Details
API Authentication (James says: Auth0, have this)
Database design for user information
Acceptance Criteria
UI with integrated login Capability, call any authenticated API
Performance: login should be smooth to a reasonable user
Security: API should not work without a valid login (token)
Testing: At least 1 automated test exists for login flow
